export interface RoleStandard {
  id: string;
  text: string;
  isCritical?: boolean;
  sopLink?: string;
  lastUpdated?: string;
  isNew?: boolean;
}

export interface RoleSection {
  id: string;
  name: string;
  standards: RoleStandard[];
  acknowledged?: boolean;
  acknowledgedDate?: string;
  hasUpdates?: boolean;
  updatesCount?: number;
}

export interface RoleDefinition {
  id: string;
  title: string;
  department: string;
  sections: RoleSection[];
  lastReviewed?: string;
  version?: string;
}

function generateId(text: string, index: number): string {
  return `std-${index}-${text.slice(0, 20).toLowerCase().replace(/[^a-z0-9]/g, '-')}`;
}

function categorizeStandards(tasks: string[]): RoleSection[] {
  const coreDuties: RoleStandard[] = [];
  const systemsProcesses: RoleStandard[] = [];
  const customerStandards: RoleStandard[] = [];
  const qualityCompliance: RoleStandard[] = [];
  const managementLeadership: RoleStandard[] = [];
  
  const systemKeywords = ['protean', 'hubspot', 'brighthr', 'hronline', 'system', 'software', 'online', 'email', 'log in', 'spreadsheet', 'document', 'tablet', 'sage', 'voip', 'microsoft', 'server', 'desktop', 'mobile'];
  const customerKeywords = ['customer', 'client', 'enquir', 'quote', 'communication', 'phone call', 'acknowledged', 'pipeline', 'proposal', 'demonstration', 'demo'];
  const qualityKeywords = ['inspection', 'review', 'check', 'audit', 'compliance', 'policy', 'procedure', 'standard', 'report', 'h&s', 'safety', 'riddor', 'fire', 'ppe', 'risk'];
  const managementKeywords = ['department', 'team', 'staff', 'training', 'appraisal', 'induction', 'manager', 'director', 'leadership', 'newsletter', 'feedback', 'entire department'];
  
  tasks.forEach((task, idx) => {
    if (task.includes('proud to work') || task.includes('praise for their work') || task.includes('comments or feedback') || task.includes('comments/feedback')) {
      return;
    }
    
    const taskLower = task.toLowerCase();
    const standard: RoleStandard = {
      id: generateId(task, idx),
      text: task,
      isCritical: taskLower.includes('critical') || taskLower.includes('quarterly rocks') || taskLower.includes('monthly report') || taskLower.includes('on time') || taskLower.includes('same-day') || taskLower.includes('within 24'),
      isNew: idx % 7 === 0,
    };
    
    if (managementKeywords.some(kw => taskLower.includes(kw))) {
      managementLeadership.push(standard);
    } else if (systemKeywords.some(kw => taskLower.includes(kw))) {
      systemsProcesses.push(standard);
    } else if (customerKeywords.some(kw => taskLower.includes(kw))) {
      customerStandards.push(standard);
    } else if (qualityKeywords.some(kw => taskLower.includes(kw))) {
      qualityCompliance.push(standard);
    } else {
      coreDuties.push(standard);
    }
  });
  
  const sections: RoleSection[] = [];
  
  if (coreDuties.length > 0) {
    sections.push({
      id: 'core-duties',
      name: 'Core Duties',
      standards: coreDuties,
      acknowledged: true,
      acknowledgedDate: '2025-11-15',
    });
  }
  
  if (customerStandards.length > 0) {
    sections.push({
      id: 'customer-standards',
      name: 'Customer Standards',
      standards: customerStandards,
      acknowledged: true,
      acknowledgedDate: '2025-11-15',
    });
  }
  
  if (systemsProcesses.length > 0) {
    sections.push({
      id: 'systems-processes',
      name: 'Systems & Processes',
      standards: systemsProcesses,
      acknowledged: false,
      hasUpdates: true,
      updatesCount: Math.min(systemsProcesses.length, 3),
    });
  }
  
  if (qualityCompliance.length > 0) {
    sections.push({
      id: 'quality-compliance',
      name: 'Quality & Compliance',
      standards: qualityCompliance,
      acknowledged: true,
      acknowledgedDate: '2025-12-01',
    });
  }
  
  if (managementLeadership.length > 0) {
    sections.push({
      id: 'management-leadership',
      name: 'Management & Leadership',
      standards: managementLeadership,
      acknowledged: false,
      hasUpdates: true,
      updatesCount: 1,
    });
  }
  
  return sections;
}

const rawRoleData: Record<string, { tasks: string[]; department: string }> = {
  'purchase-ledger-administrator': {
    department: 'Finance',
    tasks: [
      'Closing the purchasing month in 7 working days',
      'Solution-focused and able to offer creative options to clients who need more assistance',
      'Checking Statements',
      'Enter Bills and credit notes from suppliers',
      'Check and print online invoices - each month including log in and password',
      'Utilities bills log in - submit meter reading - first 5 days of the month',
      'Checking Suppliers statements',
      'Filing Bills once Simon has checked',
      'Cross hire invoices/credit notes',
      'Numatic invoices - prepare spreadsheet for correct amount',
      'Purchase ledger Email inbox',
    ],
  },
  'hs-quality-coordinator': {
    department: 'Quality',
    tasks: [
      'Review Risk assessment (Annually)',
      'Discuss and call in Peninsula for annual monitoring of our H&S company policy (Annually)',
      'Monitor that each accident or incident has been logged in accident / incident book (Monthly)',
      'Discuss actions to be taken to avoid accidents / incidents in the future (Quarterly)',
      'Organise Fire drills (Annual)',
      'Organise Fire fighting equipment / alarms are serviced (Annually)',
      'Ensure that all employees know how to report accidents and incidents',
      'Make sure that each Manager chase their staff members for completion of H&S online learning',
      'Hold regular H&S meetings (quarterly with managers to flag up any issues)',
      'When safety issues are flagged up – Act within 24 hours to action',
      'Responsible for reporting to RIDDOR of reportable accidents and incidents',
      'Fill in accreditation documents annually (Safe contractors + customer requests)',
      'Keep up to date weekly with feedbacks and actions on feedback',
      'Report to Senior management team – call meetings and set action points',
      'Do random site visits with engineers / Hire installations and Sales demonstrations',
      'Assist Operations manager in Training matrix mainly on Safety aspects',
      'Oversee so that the training fulfil our strategic goals',
      'Oversee Performance Training Matrixes and discuss budget',
      'Analyse current reports with General Manager/Operations manager',
      'Monitor email inbox to make sure we communicate to the LVC standard',
      'Review all LVC Policies and link to Processes and Procedures',
      'Review processes and assist managers when setting up procedures',
      'Support staff to improve – Find out what is needed in terms of training',
      'Support with arrangement of appraisals',
      'Organise fact finding meetings for escalation matters',
      'Organise disciplinary meetings & annually review processes',
      'Annually set up review of holiday records on HR system',
      'Quarterly overlook HR system log in to make sure details are up to date',
      'Check drivers licenses annually',
      'Check points on licenses annually',
      'Check DBS and update - 6 monthly',
      'Assess need for new staff and place adverts',
    ],
  },
  'warehouse-assistant': {
    department: 'Warehouse',
    tasks: [
      'Customer enquiries acknowledged',
      'Quote or query completed',
      'Internal enquiries acknowledged',
      'Email subject bar follows company guidance. Eg: Customer name – ES300 Quotation 23568 - LVC',
      'Workshop booking in process being followed',
      'Quarterly Rocks are set and 80%+ delivered upon',
      'Submitting monthly reports in on time',
      'Department policies are all written out, reviewed and updated regularly',
      'Additional support being requested wherever required',
      'Communication policy is followed across department',
      'Department section of Protean is clear current & informative',
      'Account Queries resolved regularly - Procedures amended to minimise re-occurrence',
      'Department operating in a professional manner, including communication and image',
      'Dispatch Via DPD (On Time)',
      'Dispatch Via Fedex (On-Time)',
      'Solution-focused and able to offer creative options to clients',
      'Booking in and allocation of items to Sales Orders',
      'Picking of Sales Orders (incomplete and complete)',
      'Warehouse Inspections - Upkeep of various zones',
      'Adding deliveries/collections to Logistics Document',
      'Chasing missing or lost deliveries with Couriers',
      'Booking and wrapping a Pallet for delivery',
    ],
  },
  'warehouse-sales-assistant': {
    department: 'Warehouse',
    tasks: [
      'Customer enquiries acknowledged',
      'Internal enquiries acknowledged',
      'Email subject bar follows company guidance',
      'Workshop booking in process being followed',
      'Quarterly Rocks are set and 80%+ delivered upon',
      'Submitting monthly reports in on time',
      'Department policies are all written out and reviewed regularly',
      'Additional support being requested wherever required',
      'Communication policy is followed across department',
      'Department section of Protean is clear current & informative',
      'Account Queries resolved regularly',
      'Department operating in a professional manner',
      'Dispatch Via DPD (On Time)',
      'Dispatch Via Fedex (On-Time)',
      'Solution-focused and able to offer creative options',
      'Booking in and allocation of items to Sales Orders',
      'Picking of Sales Orders (incomplete and complete)',
      'Warehouse Inspections - Upkeep of various zones',
      'Adding deliveries/collections to Logistics Sheet',
      'Chasing missing or lost deliveries with DPD',
      'Booking and wrapping a Pallet for delivery',
    ],
  },
  'warehouse-manager': {
    department: 'Warehouse',
    tasks: [
      'Customer enquiries acknowledged',
      'Quote or query completed',
      'Internal enquiries acknowledged',
      'Email subject bar follows company guidance',
      'Workshop booking in process being followed',
      'Quarterly Rocks are set and 80%+ delivered upon',
      'Entire department Submitting monthly reports in on time',
      'Department policies are all written out and reviewed regularly',
      'Additional support being requested wherever required',
      'Communication policy is followed across department',
      'Department section of Protean is clear current & informative',
      'Account Queries resolved regularly',
      'Department operating in a professional manner',
      'Training delivered to a high standard whenever required',
      'Engineer Van Stock Replenishment (weekly)',
      'Engineer Van Stock Take (yearly)',
      'Stock Room Stock Take (By Zone)',
      'Periodic Stock Room Inspections',
      'Picking and dispatch of Job Stock Issues',
      'Return of goods to suppliers and generate Returns note',
      'Carry out Parts to Equipment Process',
      'Creating and superseding part numbers',
    ],
  },
  'accounts-administrator': {
    department: 'Finance',
    tasks: [
      'Aged Debt',
      'Filing invoices online - Eg Serco, Dwellant, ProcureWizard',
      'Vehicle Checklists',
      'Vehicle Servicing',
      'Vehicle MOTs',
      'Vehicle Tax',
      'Engineer Timesheets',
      'Private mileage',
      'Parking fines',
      'Solution-focused and able to offer creative options',
    ],
  },
  'workshop-manager': {
    department: 'Engineering',
    tasks: [
      'Customer enquiries acknowledged',
      'Quote or query completed',
      'Internal enquiries acknowledged',
      'Email subject bar follows company guidance',
      'Workshop booking in process being followed',
      'Logistics spreadsheet being updated with as much notice as possible',
      'Quarterly Rocks are set and 80%+ delivered upon',
      'Entire department Submitting monthly reports in on time',
      'Department policies are all written out and reviewed regularly',
      'Additional support being requested wherever required',
      'Communication policy is followed across department',
      'Department section of Protean is clear current & informative',
      'Account Queries resolved regularly',
      'Department operating in a professional manner',
      'Training delivered to a high standard on set monthly date',
      'Extra training delivered to a high standard',
      'Booking Machine into Workshop procedure - use book, add tags, link job number',
      'Creation of Job on Protean',
      'Creation of Equipment on Protean',
      'Quoting Jobs (with phone call)',
      'Chasing Outstanding Jobs parts',
      'General Upkeep of Workshop',
      'Workshop Inspections',
      'Repairing machines efficiently',
      'Booking in Hire Machines, and collecting on the contract',
      'Scrapping of machinery',
      'Fitting Consumables on jobs',
      'Pre-quote explanation phone call',
      'Checking outstanding jobs with Office and chasing parts up internally',
      'Identifying parts required for jobs',
      'Expensive quote follow-up with client',
      'Book absence on HRONLINE',
      'Creation of Logistics Route - published by 3:00PM daily',
      'Monitoring and management of Logistics activities in LVC',
    ],
  },
  'sales-consultant': {
    department: 'Sales',
    tasks: [
      'Pipeline Added',
      'Customer enquiries acknowledged',
      'Quote or query completed',
      'Internal enquiries acknowledged',
      'Orders Processed',
      'Condition of your demonstration equipment',
      'Pipeline added to Hubspot',
      'Pipeline being followed up',
      'Meetings added to Hubspot',
      'All demonstration/trial machines booked out on Protean',
      'Every loan/trial machine being signed for by client',
      'Training delivered to a high standard whenever required',
      'User manual, chemical data sheet, training vid sent electronically',
      'Consumables promoted with each machine sale',
      'Service plan offered with each machine sale',
      'System to ensure all accessories come back, no damage, etc',
      'Monthly product awareness sessions being attended',
      'All demonstrations pre-qualified - decision maker will be there',
      'All clients emailed before a scheduled meeting, confirming meeting time',
      'Proposals sent to proposals@lvcuk.com',
      'Email subject bar follows company guidance',
      'Workshop booking in process being followed',
      'Sales Hire policy being followed by you/your department',
      'Photos being taken of items being delivered and dispatch note',
      'Logistics spreadsheet being checked to see if you can assist with deliveries',
      'Memo box on Protean being filled in with questions answered',
      'Solution-focused and able to offer creative options',
      'S numbers are on entire Sales fleet',
    ],
  },
  'service-coordinator': {
    department: 'Service Admin',
    tasks: [
      'Customer enquiries acknowledged',
      'Quote or query completed',
      'Internal enquiries acknowledged',
      'Email subject bar follows company guidance',
      'Workshop booking in process being followed',
      'Logistics spreadsheet being updated with as much notice as possible',
      'Quarterly Rocks are set and 80%+ delivered upon',
      'Entire department Submitting monthly reports in on time',
      'Department policies are all written out and reviewed regularly',
      'Additional support being requested wherever required',
      'Communication policy is followed across department',
      'Department section of Protean is clear current & informative',
      'Account Queries resolved regularly',
      'Department operating in a professional manner',
      'Training delivered to a high standard whenever required',
      'Logging and Allocating Breakdowns same-day',
      'Processing Further Work same-day',
      'Creating Service Contracts same-day from approval',
      'Generating and pulling through Service Visits 2 months before due date',
      'Email Inbox - General upkeep - email count kept relatively low',
      'Checking Plannerboard everyday for absences',
      'Checking previous week/day for unattended jobs',
      'Raising Breakdowns with contractors same-day',
      'Invoicing Service Jobs on same month job completed',
      'Invoicing Workshop Jobs on same month job completed',
      'Solve Engineer Timesheet and Tablet Issues same-day',
      'Notify clients each month of their upcoming service dates',
      'Customer enquiries acknowledged same-day',
      'Quote or query completed within 24h',
      'Engineer workloads and demand currently stable',
      'Callout To Be Booked list - Backlog at satisfactory levels',
      'Booking Machine into Workshop procedure - use book, add tags, link job number',
      'Solution-focused and able to offer creative options',
    ],
  },
  'delivery-driver': {
    department: 'Operations',
    tasks: [
      'Customer enquiries acknowledged',
      'Internal enquiries acknowledged',
      'Email subject bar follows company guidance',
      'Workshop booking in process being followed',
      'Logistics system being updated with as much notice as possible',
      'Quarterly Rocks are set and 80%+ delivered upon',
      'Submitting monthly reports in on time',
      'Additional support being requested wherever required',
      'Communication policy is followed',
      'Operating in a professional manner, including communication and image',
      'Training received to a high standard whenever required',
      'Health and Safety Policy followed',
      'Phone clients the day before planned route - to ensure all booked in',
      'Use Logistics System to view the planned route',
      'Gather Paperwork from each department for route',
      'Pre-dispatch check of paperwork to ensure vital information included',
      'Load Van autonomously - checking load order with route planned',
      'Phone each site when departing to complete their respective deliveries/collections',
      'Locate and correspond with the relevant site contact upon arrival to site',
      'Ask client to empty waste tank of machine before loading onto Van',
      'Carrying out correct machine loading and unloading procedure on-site',
      'Completion of route on-time for afternoon loading of following day route',
      'For pre-loaded van - depart following morning by 7:00AM',
      'For unloaded van - depart LVC by 9:00AM',
      'Complete on-site client training/demonstration to a high standard',
      'Able to answer all demonstration questions without issue',
      'Solution-focused and able to offer creative options',
    ],
  },
  'field-service-engineer': {
    department: 'Engineering',
    tasks: [
      'Are you fitting Consumables on jobs?',
      'Same-day booking in job and communication with client',
      'Ascertain Parts required for job and make sure available for visit',
      'Client Debrief (on-site. If client busy then over the phone)',
      'Quote explanation and follow-up (over £350)',
      'Checking outstanding jobs with Office and chasing parts up internally',
      'Booking in return visit to complete Callback job',
      'Completion of Reports Correctly: Labour, Equipment Notes, and Further Work',
      'Unable to attend - communication and rebooking visit',
      'Timesheets - Daily',
      'Van Stock Management',
      'Scheduling Work to stay busy',
      'Firm next-day plans and rough idea for coming 3 days',
      'Do you have a list of back-up jobs that can be attended on short notice',
      'Speaking with office if work begins to run short',
      'Pre-visit diagnosis',
      'Identifying parts required for jobs',
      'Enquiring if consumables are needed; bags, chemical, etc.',
      'Communicate the parts required to the office for job',
      'Schedule date and time with client',
      'Move the visit on your planner board once booked with client',
      'On-site client debrief',
      'Post-repair phone call to check machine is fine',
      'Book absence on HRONLINE',
      'Clients communicated to and jobs rebooked if unable to attend',
      'Service Desk updated if unable to communicate with clients',
      'Are you receiving sufficient parts in a timely manner?',
      'Do you place LVC service stickers on all machines that you service?',
      'Do you have appropriate PPE to complete your jobs safely?',
      'Do you have and wear LVC workwear on your jobs?',
      'Do you have the tools necessary to complete your daily jobs?',
      'Solution-focused and able to offer creative options',
    ],
  },
  'service-administrator': {
    department: 'Service Admin',
    tasks: [
      'Customer enquiries acknowledged',
      'Quote or query completed',
      'Internal enquiries acknowledged',
      'Email subject bar follows company guidance',
      'Workshop booking in process being followed',
      'Logistics spreadsheet being updated with as much notice as possible',
      'Submitting monthly reports in on time',
      'Additional support being requested wherever required',
      'Communication policy is followed',
      'Department section of Protean is clear current & informative',
      'Department operating in a professional manner',
      'Processing Further Work same-day',
      'Generating and pulling through Service Visits 2 months before due date',
      'Invoicing Service Jobs on same month job completed',
      'Regular checks/chasing of the job invoicing lists',
      'Logging and Allocating Breakdowns Same-Day',
      'Email Inbox - General upkeep - email count kept relatively low',
      'Notify clients each month of their upcoming service dates',
      'Callout To Be Booked list - Backlog at satisfactory levels',
      'Cancelling Old Quotes (none older than 2 months on system without reason)',
      'Awaiting Parts ETAs - Provide updates to clients',
      'Booking Machine into Workshop procedure - use book, add tags, link job number',
      'Solution-focused and able to offer creative options',
    ],
  },
  'workshop-service-engineer': {
    department: 'Engineering',
    tasks: [
      'Speed of Job Completion',
      'Internal enquiries acknowledged',
      'Email subject bar follows company guidance',
      'Workshop booking in process being followed',
      'Logistics spreadsheet being updated with as much notice as possible',
      'Submitting monthly reports in on time',
      'Communication policy is followed',
      'Training received to a high standard on set monthly date',
      'Booking Machine into Workshop procedure - use book, add tags, link job number',
      'Monitoring of Workshop Consumables and reporting insufficient stock',
      'Quoting Jobs (with phone call)',
      'Chasing Outstanding Jobs parts',
      'General Upkeep of Workshop',
      'Pre-quote explanation phone call',
      'Checking outstanding jobs with Office and chasing parts up internally',
      'Completion of Reports Correctly: Labour, Equipment Notes, and Further Work',
      'Identifying parts required for jobs',
      'Expensive quote follow-up with client',
      'Book absence on HRONLINE',
      'Solution-focused and able to offer creative options',
    ],
  },
  'operations-manager': {
    department: 'Operations',
    tasks: [
      'Key processes, procedures and standards are consistently met across department',
      'Entire department understands and conforms with company values in everything they do',
      'Customer Journey reviewed (clients and internal) finding ways to improve client satisfaction',
      'Entire team is trained and continuously developing their knowledge and skills',
      'Entire department has all the tools required to fulfil their role adequately',
      'Everyone in your department following H&S Guidelines',
      'Entire department Submitting monthly reports in on time',
      'Department policies are all written out, reviewed and updated regularly',
      'Additional support being requested wherever required',
      'Communication policy is followed across department',
      'Department section of Protean is clear current & informative',
      'Induction for all new members (incl training schedule) is set up and followed',
      'Account Queries resolved regularly',
      'Client & staff feedback being logged',
      'Periodic review meetings with your team',
      'Monthly newsletter submitted on time each month',
      'Solution-focused and able to offer creative options',
    ],
  },
  'sales-order-coordinator': {
    department: 'Sales',
    tasks: [
      'Dispatch Note Picking List (Total older than 30 days)',
      'Customer enquiries acknowledged',
      'Quote or query completed',
      'Internal enquiries acknowledged',
      'Email subject bar follows company guidance',
      'Workshop booking in process being followed',
      'Logistics spreadsheet being updated with as much notice as possible',
      'Submitting monthly reports in on time',
      'Additional support being requested wherever required',
      'Communication policy is followed',
      'Department section of Protean is clear current & informative',
      'Department operating in a professional manner',
      'Solution-focused and able to offer creative options',
      'Creating and processing Sales Orders',
      'Chasing Parts with suppliers',
      'Email Inbox upkeep',
      'Checking the picking dispatch note list and completing where possible',
      'Placing direct delivery POs with suppliers',
      'Updating and monitoring the Pending logistics list',
      'Chasing and closing down of quotes',
    ],
  },
  'sales-director': {
    department: 'Executive',
    tasks: [
      'Key processes, procedures and standards are consistently met across department',
      'Entire department understands and conforms with company values in everything they do',
      'Customer Journey reviewed (clients and internal) finding ways to improve client satisfaction',
      'Entire team is trained and continuously developing their knowledge and skills',
      'Entire department has all the tools required to fulfil their role adequately',
      'Everyone in your department following H&S Guidelines',
      'Entire department Submitting monthly reports in on time',
      'Department policies are all written out, reviewed and updated regularly',
      'Additional support being requested wherever required',
      'Communication policy is followed across department',
      'Department section of Protean is clear current & informative',
      'Induction for all new members (incl training schedule) is set up and followed',
      'Account Queries resolved regularly',
      'Client & staff feedback being logged',
      'Periodic review meetings with your team',
      'Annual appraisal held with individuals within your team',
      'Monthly newsletter submitted on time each month',
      'Department operating in a professional manner',
      'Customer enquiries acknowledged',
      'Quote or query completed',
      'Internal enquiries acknowledged',
      'Orders Processed',
      'Condition of your demonstration equipment',
      'Pipeline added to Hubspot',
      'Pipeline being followed up',
      'Meetings added to Hubspot',
      'All demonstration/trial machines booked out on Protean',
      'Every loan/trial machine being signed for by client',
      'Training delivered to a high standard whenever required',
      'User manual, chemical data sheet, training vid sent electronically',
      'Consumables promoted with each machine sale',
      'Service plan offered with each machine sale',
      'System to ensure all accessories come back, no damage, etc',
      'Monthly product awareness sessions being attended',
      'All demonstrations pre-qualified - decision maker will be there',
      'All clients emailed before a scheduled meeting',
      'Proposals sent to proposals@lvcuk.com',
      'Email subject bar follows company guidance',
      'Workshop booking in process being followed',
      'Sales Hire policy being followed by you/your department',
      'Photos being taken of items being delivered and dispatch note',
      'Logistics spreadsheet being checked to see if you can assist with deliveries',
      'Memo box on Protean being filled in with questions answered',
      'Solution-focused and able to offer creative options',
      'S numbers are on entire Sales fleet',
    ],
  },
  'accounts-manager': {
    department: 'Finance',
    tasks: [
      'Key processes, procedures and standards are consistently met across department',
      'Entire department understands and conforms with company values',
      'Customer Journey reviewed (clients and internal)',
      'Entire team is trained and continuously developing',
      'Entire department has all the tools required to fulfil their role',
      'Everyone in your department following H&S Guidelines',
      'Entire department Submitting monthly reports in on time',
      'Department policies are all written out, reviewed and updated regularly',
      'Additional support being requested wherever required',
      'Communication policy is followed across department',
      'Department section of Protean is clear current & informative',
      'Induction for all new members is set up and followed',
      'Account Queries resolved regularly',
      'Client & staff feedback being logged',
      'Periodic review meetings with your team',
      'Annual appraisal held with individuals within your team',
      'Monthly newsletter submitted on time each month',
      'Department operating in a professional manner',
      'Solution-focused and able to offer creative options',
      'Managing email inboxes - Accounts, Info, purchase Ledger',
      'Mail order invoices',
      'Credit Notes',
      'Machine sale register with Inv no, Serial no, etc',
      'Long term invoices each month',
      'Bad Debt chasing',
      'Check all bank accounts /balance in the morning',
      'Pay off customer payments from RBS bank statement',
      'Bank Reconciliation - Current acc, RBS Acc',
      'Yearly contract renewal, invoice as soon as service visit is done',
      'Oversee big contracts when due',
      'Wages and Bonus - Engineers, Salesman, Hire',
      'Director assistance - any work issues, cashflow, reports',
      'Paying suppliers - monitoring due dates',
      'General staff assistance',
      'Journal entries for loans, HP interest',
      'RBS reports, notify on Facflow',
      'Prepare for VAT',
      'Engineer/salesmen expenses, float, loan',
      'Manage Petty cash, recycle income',
      'Credit card receipts chase, claim VAT',
      'Make changes if other makes mistakes on Sage',
      'Taking phone calls, or make calls to sort out accounts queries',
      'Protean - End of month reports after closing the month',
      'Daily filing',
      'Send details to customers, new acc application form',
      'Check and inform if any jobs, mail orders are wrong',
      'Checking if payment received but not invoiced',
      'Spend time learning and improving departments use of Protean',
      'Closing month procedure - Sales',
      'Closing month procedure - Purchasing',
      'RBS Audits',
      'Preparing and logging department performance figures',
      'Keep track online for PAYE & VAT',
      'Reaching deadlines',
      'Checking picking to picking status',
      'Opening post',
      'Entering RBS bacs and cheques payments from customer',
      'Taking Visa payments from customers',
      'Support purchase Ledger queries',
      'Getting Nilfisk Bills ready for month end',
      'Daily despatch notes filing',
      'Opening accounts for New customers',
      'Checking spread sheet against Protean',
      'Enter Fimap, Amazon, any invoices paid by credit card',
      'Scan documents',
    ],
  },
  'general-manager': {
    department: 'Executive',
    tasks: [
      'Key processes, procedures and standards are consistently met across department',
      'Entire department understands and conforms with company values',
      'Customer Journey reviewed (clients and internal)',
      'Entire team is trained and continuously developing',
      'Entire department has all the tools required to fulfil their role',
      'Everyone in your department following H&S Guidelines',
      'Entire department Submitting monthly reports in on time',
      'Department policies are all written out, reviewed and updated regularly',
      'Additional support being requested wherever required',
      'Communication policy is followed across department',
      'Department section of Protean is clear current & informative',
      'Induction for all new members is set up and followed',
      'Account Queries resolved regularly',
      'Client & staff feedback being logged',
      'Periodic review meetings with your team',
      'Annual appraisal held with individuals within your team',
      'Monthly newsletter submitted on time each month',
      'Department operating in a professional manner',
      'Customer enquiries acknowledged',
      'Quote or query completed',
      'Internal enquiries acknowledged',
      'Orders Processed',
      'Condition of your demonstration equipment',
      'Pipeline added to Hubspot',
      'Pipeline being followed up',
      'Meetings added to Hubspot',
      'All demonstration/trial machines booked out on Protean',
      'Every loan/trial machine being signed for by client',
      'Training delivered to a high standard whenever required',
      'User manual, chemical data sheet, training vid sent electronically',
      'Consumables promoted with each machine sale',
      'Service plan offered with each machine sale',
      'System to ensure all accessories come back, no damage, etc',
      'Monthly product awareness sessions being attended',
      'All demonstrations pre-qualified - decision maker will be there',
      'All clients emailed before a scheduled meeting',
      'Proposals sent to proposals@lvcuk.com',
      'Email subject bar follows company guidance',
      'Workshop booking in process being followed',
      'Sales Hire policy being followed',
      'Photos being taken of items being delivered and dispatch note',
      'Logistics spreadsheet being checked',
      'Memo box on Protean being filled in',
      'Solution-focused and able to offer creative options',
      'S numbers are on entire Sales fleet',
    ],
  },
  'hire-department-manager': {
    department: 'Operations',
    tasks: [
      'Key processes, procedures and standards are consistently met across department',
      'Entire department understands and conforms with company values',
      'Customer Journey reviewed (clients and internal)',
      'Entire team is trained and continuously developing',
      'Entire department has all the tools required to fulfil their role',
      'Everyone in your department following H&S Guidelines',
      'Entire department Submitting monthly reports in on time',
      'Department policies are all written out, reviewed and updated regularly',
      'Additional support being requested wherever required',
      'Communication policy is followed across department',
      'Department section of Protean is clear current & informative',
      'Induction for all new members is set up and followed',
      'Account Queries resolved regularly',
      'Client & staff feedback being logged',
      'Periodic review meetings with your team',
      'Annual appraisal held with individuals within your team',
      'Monthly newsletter submitted on time each month',
      'Department operating in a professional manner',
      'Customer enquiries acknowledged',
      'Quote or query completed',
      'Internal enquiries acknowledged',
      'Hire go ahead processed',
      'Condition of Hire Fleet',
      'Hire fleet able to meet quantity of client demand',
      'Off hire report sent to client within 72 hours',
      'Training delivered to a high standard whenever required',
      'User manual, chemical data sheet, training vid sent electronically on all hires',
      'Laminated User guide physically given on each hire',
      'Consumables promoted with each hire',
      'Invoicing completed within correct month',
      'Entire fleet being regularly serviced',
      'System to ensure all accessories come back, damage charged, etc',
      'Recurring meetings with Accounts, Service & Workshop',
      'Confidence in machines not being left on clients site at end of hire',
      'All quotes are sent to clients in writing',
      'All proposals sent to proposals@lvcuk.com',
      'Pipeline added to Hubspot',
      'Pipeline being followed up',
      'Meetings added to Hubspot',
      'Photos being taken delivered items and despatch note',
      'Sales Hire policy being followed by you/your department',
      'H numbers are on entire Hire fleet',
      'Business case being sent through on any new machine requirements',
      'Hire contracts sent and agreed in writing on all hires',
      'Email subject bar follows company guidance',
      'Workshop booking in process being followed',
      'Logistics spreadsheet being updated with as much notice as possible',
      'Potential hires being added to logistics spreadsheet',
      'Contract notes section filled out with all required information',
      'Solution-focused and able to offer creative options',
    ],
  },
  'it-procurement-manager': {
    department: 'IT',
    tasks: [
      'Parts Outstanding by Supplier (total number)',
      'Disaster Recovery',
      'Virus Protection',
      'Desktop computers',
      'Mobile phones & Tablets',
      'Protean - System',
      'Protean - Prices',
      'Microsoft Teams',
      'Servers - General Condition',
      'Efficient file storage',
      'VOIP',
      'How often are you reviewing the hardware we use to maximise productivity?',
      'How often are you reviewing the software we use to maximise productivity?',
      'Rectifying of day to day user IT issues',
      'Customer enquiries acknowledged',
      'Quote or query completed',
      'Internal enquiries acknowledged',
      'Email subject bar follows company guidance',
      'Logistics spreadsheet being updated with as much notice as possible',
      'Quarterly Rocks are set and 80%+ delivered upon',
      'Submitting monthly reports in on time',
      'Additional support being requested wherever required',
      'Communication policy is followed',
      'Department section of Protean is clear current & informative',
      'Account Queries resolved regularly',
      'Department operating in a professional manner',
      'Regular creation of purchase orders to fulfil demand',
      'Splitting of Purchase orders by demand vs. stock',
      'Solution-focused and able to offer creative options',
    ],
  },
  'senior-service-engineer': {
    department: 'Engineering',
    tasks: [
      'Are you fitting Consumables on jobs?',
      'Same-day booking in job and communication with client',
      'Ascertain Parts required for job and make sure available for visit',
      'Client Debrief (on-site. If client busy then over the phone, or by email)',
      'Quote explanation and follow-up (over £350)',
      'Checking outstanding jobs with Office and chasing parts up internally',
      'Booking in return visit to complete Callback job',
      'Completion of Reports Correctly: Labour, Equipment Notes, and Further Work',
      'Unable to attend - communication and rebooking visit',
      'Timesheets - Daily',
      'Van Stock Management',
      'Scheduling Work to stay busy',
      'Firm next-day plans and rough idea for coming 3 days',
      'Do you have a list of back-up jobs that can be attended on short notice',
      'Speaking with office if work begins to run short',
      'Pre-visit diagnosis',
      'Identifying parts required for jobs',
      'Enquiring if consumables are needed; bags, chemical, etc.',
      'Communicate the parts required to the office for job',
      'Schedule date and time with client',
      'Move the visit on your planner board once booked with client',
      'Post-repair phone call to check machine is fine',
      'Book absence on BrightHR',
      'Service Desk updated if unable to communicate with clients',
      'Checking client history before visiting site',
      'Mentoring junior engineers on technical skills',
      'Providing technical guidance to Workshop team',
      'First point of escalation for complex faults',
      'Contributing to training materials and sessions',
      'Solution-focused and able to offer creative options',
    ],
  },
};

export const roleDefinitions: Record<string, RoleDefinition> = {};

Object.entries(rawRoleData).forEach(([id, data]) => {
  const titleMap: Record<string, string> = {
    'purchase-ledger-administrator': 'Purchase Ledger Administrator',
    'hs-quality-coordinator': 'H&S & Quality Coordinator',
    'warehouse-assistant': 'Warehouse Assistant',
    'warehouse-sales-assistant': 'Warehouse and Sales Assistant',
    'warehouse-manager': 'Warehouse Manager',
    'accounts-administrator': 'Accounts Administrator',
    'workshop-manager': 'Workshop Manager / Senior Service Engineer',
    'sales-consultant': 'Sales Consultant',
    'service-coordinator': 'Service Co-Ordinator',
    'delivery-driver': 'Delivery Driver',
    'field-service-engineer': 'Field Service Engineer',
    'service-administrator': 'Service Administrator',
    'workshop-service-engineer': 'Workshop Service Engineer',
    'operations-manager': 'Operations Manager',
    'sales-order-coordinator': 'Sales Order Coordinator',
    'sales-director': 'Sales Director',
    'accounts-manager': 'Accounts Manager',
    'general-manager': 'General Manager',
    'hire-department-manager': 'Hire Department Manager',
    'it-procurement-manager': 'IT & Procurement Manager',
    'senior-service-engineer': 'Senior Service Engineer',
  };

  roleDefinitions[id] = {
    id,
    title: titleMap[id] || id.split('-').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' '),
    department: data.department,
    version: `${Math.floor(Math.random() * 3) + 1}.${Math.floor(Math.random() * 9)}`,
    lastReviewed: `2025-${String(Math.floor(Math.random() * 3) + 10).padStart(2, '0')}-${String(Math.floor(Math.random() * 28) + 1).padStart(2, '0')}`,
    sections: categorizeStandards(data.tasks),
  };
});

export const rolesList = Object.values(roleDefinitions);

export function getRoleById(id: string): RoleDefinition | undefined {
  return roleDefinitions[id];
}

export function getRolesByDepartment(department: string): RoleDefinition[] {
  return rolesList.filter(role => role.department.toLowerCase() === department.toLowerCase());
}

export function getTotalUpdatesCount(role: RoleDefinition): number {
  return role.sections.reduce((sum, section) => sum + (section.updatesCount || 0), 0);
}

export function getAcknowledgedSectionsCount(role: RoleDefinition): number {
  return role.sections.filter(s => s.acknowledged).length;
}

export function getAllRefresherRequests(): { roleId: string; roleTitle: string; sectionId: string; sectionName: string; requestedBy: string; requestedDate: string }[] {
  return [
    { roleId: 'field-service-engineer', roleTitle: 'Field Service Engineer', sectionId: 'systems-processes', sectionName: 'Systems & Processes', requestedBy: 'David Thompson', requestedDate: '2026-01-08' },
    { roleId: 'warehouse-assistant', roleTitle: 'Warehouse Assistant', sectionId: 'core-duties', sectionName: 'Core Duties', requestedBy: 'Tom Richards', requestedDate: '2026-01-05' },
    { roleId: 'service-administrator', roleTitle: 'Service Administrator', sectionId: 'customer-standards', sectionName: 'Customer Standards', requestedBy: 'Emma Clarke', requestedDate: '2026-01-09' },
    { roleId: 'sales-consultant', roleTitle: 'Sales Consultant', sectionId: 'systems-processes', sectionName: 'Systems & Processes', requestedBy: 'James Wilson', requestedDate: '2026-01-10' },
  ];
}

export function getRoleOptions(): { value: string; label: string; department: string }[] {
  return rolesList.map(role => ({
    value: role.id,
    label: role.title,
    department: role.department,
  }));
}
