export interface SurveyTask {
  id: string;
  text: string;
  isFeedback?: boolean;
}

export interface RoleSurvey {
  roleId: string;
  roleTitle: string;
  tasks: SurveyTask[];
}

const rawSurveyData: Record<string, string[]> = {
  "Purchase Ledger administrator": [
    "Closing the purchasing month in 7 working days",
    "Solution-focused and able to offer creative options to clients who need more assistance.",
    "Checking Statements",
    "Enter Bills and credit notes from suppliers",
    "check and print online invoices - each month incluling log in and password",
    "Utilities bills log in - submit meter reading - first 5 days of the month",
    "Checking Suppliers statements",
    "Filing Bills once Simon has checked",
    "cross hire invoices/credit notes",
    "Numatic invoices - prepare spreadsheet for correct amount",
    "Purchase ledger Email inbox",
    "Are you proud to work at LVC?",
    "Is there an individual or department that you would like to praise for their work recently?",
    "Do you have any comments or feedback you wish to provide?"
  ],
  "H&S & Quality Coordinator": [
    "Review Risk assessment (Annually)",
    "Discuss and call in Peninsula for annual monitoring of our H&S company policy (Annually)",
    "Monitor that each accident or incident has been logged in accident / incident book. (Monthly)",
    "Discuss actions to be taken to avoid accidents / incidents in the future (Quarterly)",
    "Organise Fire drills (Annual)",
    "Organise Fire fighting equipment / alarms are serviced (Annually)",
    "Ensure that all employees know how to report accidents and incidents and introduce new employees to this procedure.",
    "Make sure that each Manager chase their staff members for completion of H&S online learning are completed (Annually)",
    "Hold regular H&S meetings (quarterly – Dec/March/June/Sept with managers to flag up any issues",
    "When safety issues are flagged up – Act within 24 hours to action",
    "Responsible for reporting to RIDDOR of reportable accidents and incidents.",
    "Solution-focused and able to offer creative options to clients who need more assistance.",
    "Fill in accreditation documents annually (Safe contractors + customer requests)",
    "Keep up to date weekly with feedback's and actions on feedback and summarise in one place",
    "Report to Senior management team – call meetings and set action points to rectify",
    "Do random site visits with engineers / Hire installations and Sales demonstrations",
    "Assist Operations manager in Training matrix mainly on Safety aspects",
    "Oversee so that the training fulfil our strategic goals. Assist in the development of training manual and choice of courses.",
    "Oversee Performance Training Matrixes and discuss budget for further training with Directors",
    "Analyse current reports with General Manager/Operations manager and assist with presentation on board meeting",
    "Monitor 'drop in' – random into each persons email inbox to make sure that we communicate to the LVC standard",
    "Review all LVC Policies and link to Processes and Procedures. (annual overview)",
    "Review processes and assist managers when setting up procedures",
    "Support staff to improve – Find out what is needed in terms of training or understanding.",
    "Support with arrangement of appraisals",
    "Organise fact finding meetings for escalation matters & annually review processes",
    "Organise disciplinary meetings & annually review processes for these",
    "Annually set up review of holiday records on HR system",
    "Quarterly overlook HR system log in to make sure details are up to date",
    "Check drivers licenses annually",
    "Check points on licenses annually",
    "Check DBS and update - 6 monthly",
    "Assess need for new staff and place adverts - communicate need based on our current targets",
    "Are you proud to work at LVC?",
    "Is there an individual or department that you would like to praise for their work recently?",
    "Do you have any comments or feedback you wish to provide?"
  ],
  "Warehouse Assistant": [
    "Customer enquiries acknowledged",
    "Quote or query completed",
    "Internal enquiries acknowledged",
    "Email subject bar follows company guidance. Eg: Customer name – ES300 Quotation 23568 - LVC",
    "Workshop booking in process being followed",
    "Quarterly Rocks are set and 80%+ delivered upon",
    "Submitting monthly reports in on time",
    "Department policies are all written out, reviewed and updated regularly - maximising efficiencies",
    "Additional support being requested wherever required (after efficiencies within dept have been maximised",
    "Communication policy is followed across department",
    "Department section of Protean is clear current & informative",
    "Account Queries resolved regularly - Procedures amended to minimise re-occurrence",
    "Department operating in a professional manner, including communication and image.",
    "Dispatch Via DPD (On Time)",
    "Dispatch Via Fedex (On-Time)",
    "Solution-focused and able to offer creative options to clients who need more assistance.",
    "Booking in and allocation of items to Sales Orders",
    "Picking of Sales Orders (incomplete and complete)",
    "Warehouse Inspections - Upkeep of various zones",
    "Adding deliveries/collections to Logistics Document",
    "Chasing missing or lost deliveries with Couriers",
    "Booking and wrapping a Pallet for delivery",
    "Are you proud to work at LVC?",
    "Is there an individual or department that you would like to praise for their work recently?",
    "Do you have any comments or feedback you wish to provide?"
  ],
  "Warehouse Manager": [
    "Customer enquiries acknowledged",
    "Quote or query completed",
    "Internal enquiries acknowledged",
    "Email subject bar follows company guidance. Eg: Customer name – ES300 Quotation - LVC 23568",
    "Workshop booking in process being followed",
    "Quarterly Rocks are set and 80%+ delivered upon",
    "Entire department Submitting monthly reports in on time",
    "Department policies are all written out, reviewed and updated regularly - maximising efficiencies",
    "Additional support being requested wherever required (after efficiencies within dept have been maximised",
    "Communication policy is followed across department",
    "Department section of Protean is clear current & informative",
    "Account Queries resolved regularly - Procedures amended to minimise re-occurrence",
    "Department operating in a professional manner, including communication and image.",
    "Training delivered to a high standard whenever required",
    "Engineer Van Stock Replenishment (weekly)",
    "Engineer Van Stock Take (yearly)",
    "Stock Room Stock Take (By Zone)",
    "Solution-focused and able to offer creative options to clients who need more assistance.",
    "Periodic Stock Room Inspections",
    "Picking and dispatch of Job Stock Issues",
    "Return of goods to suppliers and generate Returns note",
    "Carry out Parts to Equipment Process",
    "Creating and superseding part numbers",
    "Are you proud to work at LVC?",
    "Is there an individual or department that you would like to praise for their work recently?",
    "Do you have any comments or feedback you wish to provide?"
  ],
  "Accounts Administrator": [
    "Aged Debt",
    "Filing invoices online - Eg Serco, Dwellant, ProcureWizard",
    "Vehicle Checklists",
    "Vehicle Servicing",
    "Vehicle MOTs",
    "Vehicle Tax",
    "Engineer Timesheets",
    "Private mileage",
    "Parking fines",
    "Solution-focused and able to offer creative options to clients who need more assistance.",
    "Are you proud to work at LVC?",
    "Is there an individual or department that you would like to praise for their work recently?",
    "Do you have any comments or feedback you wish to provide?"
  ],
  "Workshop Manager": [
    "Customer enquiries acknowledged",
    "Quote or query completed",
    "Internal enquiries acknowledged",
    "Email subject bar follows company guidance. Eg: Customer name – ES300 Quotation 23568 - LVC",
    "Workshop booking in process being followed",
    "Logistics spreadsheet being updated with as much notice as possible",
    "Quarterly Rocks are set and 80%+ delivered upon",
    "Entire department Submitting monthly reports in on time",
    "Department policies are all written out, reviewed and updated regularly - maximising efficiencies",
    "Additional support being requested wherever required (after efficiencies within dept have been maximised",
    "Communication policy is followed across department",
    "Department section of Protean is clear current & informative",
    "Account Queries resolved regularly - Procedures amended to minimise re-occurrence",
    "Department operating in a professional manner, including communication and image.",
    "Training delivered to a high standard on set monthly date",
    "Extra training delivered to a high standard",
    "Booking Machine into Workshop procedure - use book, add tags, link job number.",
    "Creation of Job on Protean",
    "Creation of Equipment on Protean",
    "Quoting Jobs (with phone call)",
    "Chasing Outstanding Jobs' parts",
    "General Upkeep of Workshop",
    "Workshop Inspections",
    "Repairing machines efficiently",
    "Booking in Hire Machines, and collecting on the contract",
    "Scrapping of machinery",
    "Are you fitting Consumables on jobs?",
    "Pre-quote explanation phone call 'Just want to make sure you have all the information you need'",
    "Checking outstanding jobs with Office and chasing parts up internally",
    "Identifying parts required for jobs",
    "Expensive quote follow-up with client",
    "Book absence on HRONLINE, and mention in notes on whether clients have been contacted or not",
    "Creation of Logistics Route - published by 3:00PM daily",
    "Solution-focused and able to offer creative options to clients who need more assistance.",
    "Monitoring and management of Logistics activities in LVC",
    "Are you proud to work at LVC?",
    "Is there an individual or department that you would like to praise for their work recently?",
    "Do you have any comments or feedback you wish to provide?"
  ],
  "Sales Consultant": [
    "Pipeline Added",
    "Customer enquiries acknowledged",
    "Quote or query completed",
    "Internal enquiries acknowledged",
    "Orders Processed",
    "Condition of your demonstration equipment",
    "Pipeline added to Hubspot",
    "Pipeline being followed up",
    "Meetings added to Hubspot",
    "All demonstration/trial machines booked out on Protean",
    "Every loan/trial machine being signed for by client",
    "Training delivered to a high standard whenever required",
    "User manual, chemical data sheet, training vid sent electronically",
    "Consumables promoted with each machine sale",
    "Service plan offered with each machine sale",
    "System to ensure all accessories come back, no damage, etc",
    "Monthly product awareness sessions being attended",
    "All demonstrations pre-qualified - decision maker will be there",
    "All clients emailed before a scheduled meeting, confirming meeting time and that it is still going ahead.",
    "Proposals sent to proposals@lvcuk.com",
    "Email subject bar follows company guidance. Eg: Customer name – ES300 Quotation 23568 - LVC",
    "Workshop booking in process being followed",
    "Sales Hire policy being followed by you/your department",
    "Photos being taken of items being delivered and dispatch note. Emailed to deliveryphotos@lvcuk.com",
    "Logistics spreadsheet being checked to see if you can assist with deliveries",
    "Memo box on Protean being filled in with questions answered",
    "Solution-focused and able to offer creative options to clients who need more assistance.",
    "S numbers are on entire Sales fleet",
    "Are you proud to work at LVC?",
    "Is there an individual or department that you would like to praise for their work recently?",
    "Do you have any comments or feedback you wish to provide?"
  ],
  "Service Coordinator": [
    "Customer enquiries acknowledged",
    "Quote or query completed",
    "Internal enquiries acknowledged",
    "Email subject bar follows company guidance. Eg: Customer name – ES300 Quotation - LVC 23568",
    "Workshop booking in process being followed",
    "Logistics spreadsheet being updated with as much notice as possible",
    "Quarterly Rocks are set and 80%+ delivered upon",
    "Entire department Submitting monthly reports in on time",
    "Department policies are all written out, reviewed and updated regularly - maximising efficiencies",
    "Additional support being requested wherever required (after efficiencies within dept have been maximised",
    "Communication policy is followed across department",
    "Department section of Protean is clear current & informative",
    "Account Queries resolved regularly - Procedures amended to minimise re-occurrence",
    "Department operating in a professional manner, including communication and image",
    "Training delivered to a high standard whenever required",
    "Logging and Allocating Breakdowns same-day",
    "Processing Further Work same-day",
    "Creating Service Contracts same-day from approval",
    "Generating and pulling through Service Visits 2 months before due date",
    "Email Inbox - General upkeep - email count kept relatively low",
    "Checking Plannerboard everyday for absences",
    "Checking previous week/day for unattended jobs - procedure for addressing and moving visit",
    "Raising Breakdowns with contractors same-day",
    "Invoicing Service Jobs on same month job completed",
    "Invoicing Workshop Jobs on same month job completed",
    "Solve Engineer Timesheet and Tablet Issues same-day",
    "Notify clients each month of their upcoming service dates",
    "Customer enquiries acknowledged same-day",
    "Quote or query completed within 24h",
    "Engineer workloads and demand currently stable",
    "Callout To Be Booked list - Backlog at satisfactory levels",
    "Booking Machine into Workshop procedure - use book, add tags, link job number.",
    "Solution-focused and able to offer creative options to clients who need more assistance.",
    "Are you proud to work at LVC?",
    "Is there an individual or department that you would like to praise for their work recently?",
    "Do you have any comments/feedback you wish to make?"
  ],
  "Delivery Driver": [
    "Customer enquiries acknowledged",
    "Internal enquiries acknowledged",
    "Email subject bar follows company guidance. Eg: Customer name – ES300 Quotation 23568 - LVC",
    "Workshop booking in process being followed",
    "Logistics system being updated with as much notice as possible",
    "Quarterly Rocks are set and 80%+ delivered upon",
    "Submitting monthly reports in on time",
    "Additional support being requested wherever required",
    "Communication policy is followed",
    "Operating in a professional manner, including communication and image.",
    "Training received to a high standard whenever required",
    "Health and Safety Policy followed",
    "Phone clients the day before planned route - to ensure all booked in and item/s ready",
    "Use Logistics System to view the planned route",
    "Gather Paperwork from each department for route",
    "Pre-dispatch check of paperwork to ensure vital information included (ie. contact details)",
    "Load Van autonomously - checking load order with route planned",
    "Phone each site when departing to complete their respective deliveries/collections",
    "Locate and correspond with the relevant site contact upon arrival to site",
    "Ask client to empty waste tank of machine before loading onto Van",
    "Carrying out correct machine loading and unloading procedure on-site",
    "Completion of route on-time for afternoon loading of following day's route",
    "For pre-loaded van - depart following morning by 7:00AM",
    "For unloaded van - depart LVC by 9:00AM",
    "Complete on-site client training/demonstration to a high standard",
    "Able to answer all demonstration questions without issue",
    "Solution-focused and able to offer creative options to clients who need more assistance.",
    "Are you proud to work at LVC?",
    "Is there an individual or department that you would like to praise for their work recently?",
    "Do you have any comments or feedback you wish to provide?"
  ],
  "Field Service Engineer": [
    "Are you fitting Consumables on jobs?",
    "Same-day booking in job and communication with client",
    "Ascertain Parts required for job and make sure available for visit",
    "Client Debrief (on-site. If client busy then over the phone)",
    "Quote explanation and follow-up (over £350) 'Just want to make sure you have all the information you need'",
    "Checking outstanding jobs with Office and chasing parts up internally",
    "Booking in return visit to complete Callback job - respond to 'Parts in' email additionally",
    "Completion of Reports Correctly: Labour, Equipment Notes, and Further Work",
    "Unable to attend - communication and rebooking visit",
    "Timesheets - Daily",
    "Van Stock Management",
    "Scheduling Work to stay busy",
    "Firm next-day plans and rough idea for coming 3 days",
    "Do you have a list of back-up jobs that can be attended on short notice",
    "Speaking with office if work begins to run short",
    "Pre-visit diagnosis",
    "Identifying parts required for jobs",
    "Enquiring if consumables are needed; bags, chemical, etc.",
    "Communicate the parts required to the office for job",
    "Schedule date and time with client",
    "Move the visit on your planner board once booked with client",
    "On-site client debrief",
    "Post-repair phone call to check machine is fine",
    "Book absence on HRONLINE, and mention in notes on whether clients have been contacted or not",
    "Clients communicated to and jobs rebooked if unable to attend",
    "Service Desk updated if unable to communicate with clients.",
    "Are you receiving sufficient parts in a timely manner?",
    "Do you place LVC service stickers on all machines that you service?",
    "Do you have appropriate PPE to complete your jobs safely?",
    "Do you have and wear LVC workwear on your jobs?",
    "Do you have the tools necessary to complete your daily jobs?",
    "Solution-focused and able to offer creative options to clients who need more assistance.",
    "Are you proud to work at LVC?",
    "Is there an individual or department that you would like to praise for their work recently?",
    "Do you have any comments/feedback you wish to make?"
  ],
  "Service Administrator": [
    "Customer enquiries acknowledged",
    "Quote or query completed",
    "Internal enquiries acknowledged",
    "Email subject bar follows company guidance. Eg: Customer name – ES300 Quotation 23568 - LVC",
    "Workshop booking in process being followed",
    "Logistics spreadsheet being updated with as much notice as possible",
    "Submitting monthly reports in on time",
    "Additional support being requested wherever required",
    "Communication policy is followed",
    "Department section of Protean is clear current & informative",
    "Department operating in a professional manner, including communication and image",
    "Processing Further Work same-day",
    "Generating and pulling through Service Visits 2 months before due date",
    "Invoicing Service Jobs on same month job completed",
    "Regular checks/chasing of the job invoicing lists: Awaiting Complete, Awaiting Details, Authorise Required",
    "Logging and Allocating Breakdowns Same-Day",
    "Email Inbox - General upkeep - email count kept relatively low",
    "Notify clients each month of their upcoming service dates",
    "Callout To Be Booked list - Backlog at satisfactory levels",
    "Cancelling Old Quotes (none older than 2 months on system without reason)",
    "Awaiting Parts ETAs - Provide updates to clients",
    "Booking Machine into Workshop procedure - use book, add tags, link job number.",
    "Solution-focused and able to offer creative options to clients who need elevated assistance.",
    "Are you proud to work at LVC?",
    "Is there an individual or department that you would like to praise for their work recently?",
    "Do you have any comments/feedback you wish to make?"
  ],
  "Workshop Service Engineer": [
    "Speed of Job Completion",
    "Internal enquiries acknowledged",
    "Email subject bar follows company guidance. Eg: Customer name – ES300 Quotation 23568 - LVC",
    "Workshop booking in process being followed",
    "Logistics spreadsheet being updated with as much notice as possible",
    "Submitting monthly reports in on time",
    "Communication policy is followed",
    "Training received to a high standard on set monthly date",
    "Booking Machine into Workshop procedure - use book, add tags, link job number.",
    "Monitoring of Workshop Consumables and reporting insufficient stock",
    "Quoting Jobs (with phone call)",
    "Chasing Outstanding Jobs' parts",
    "General Upkeep of Workshop",
    "Pre-quote explanation phone call 'Just want to make sure you have all the information you need'",
    "Checking outstanding jobs with Office and chasing parts up internally",
    "Completion of Reports Correctly: Labour, Equipment Notes, and Further Work",
    "Identifying parts required for jobs",
    "Expensive quote follow-up with client",
    "Book absence on HRONLINE, and mention in notes on whether clients have been contacted or not",
    "Solution-focused and able to offer creative options to clients who need more assistance.",
    "Are you proud to work at LVC?",
    "Is there an individual or department that you would like to praise for their work recently?",
    "Do you have any comments or feedback you wish to provide?"
  ],
  "Operations Manager": [
    "Key processes, procedures and standards are consistently met across department, including periods of holidays & sickness.",
    "Entire department understands and conforms with company values in everything they do.",
    "Customer enquiries acknowledged same-day",
    "Quote or query completed within 24h",
    "Internal enquiries acknowledged same-day",
    "Email subject bar follows company guidance. Eg: Customer name – ES300 Quotation - LVC 23568",
    "Quarterly Rocks are set and 80%+ delivered upon",
    "Entire department Submitting monthly reports in on time",
    "Department policies are all written out, reviewed and updated regularly - maximising efficiencies",
    "Additional support being requested wherever required (after efficiencies within dept have been maximised",
    "Communication policy is followed across department",
    "Department section of Protean is clear current & informative",
    "Account Queries resolved regularly - Procedures amended to minimise re-occurrence",
    "Department operating in a professional manner, including communication and image.",
    "Training delivered to a high standard whenever required",
    "Logging and Allocating Breakdowns same-day",
    "Processing Further Work same-day",
    "Creating Service Contracts same-day from approval",
    "Generating and pulling through Service Visits 2 months before due date",
    "Email Inbox - General upkeep - email count kept relatively low",
    "Checking Plannerboard everyday for absences",
    "Checking previous week/day for unattended jobs - procedure for addressing and moving visit",
    "Raising Breakdowns with contractors same-day",
    "Invoicing Service Jobs on same month job completed",
    "Invoicing Workshop Jobs on same month job completed",
    "Solve Engineer Timesheet and Tablet Issues same-day",
    "Notify clients each month of their upcoming service dates",
    "Engineer workloads and demand currently stable",
    "Callout To Be Booked list - Backlog at satisfactory levels",
    "Solution-focused and able to offer creative options to clients who need more assistance.",
    "Are you proud to work at LVC?",
    "Is there an individual or department that you would like to praise for their work recently?",
    "Do you have any comments or feedback you wish to provide?"
  ],
  "Hire Controller": [
    "Customer enquiries acknowledged",
    "Quote or query completed",
    "Internal enquiries acknowledged",
    "Email subject bar follows company guidance. Eg: Customer name – ES300 Quotation - LVC 23568",
    "Logistics spreadsheet being updated with as much notice as possible",
    "Quarterly Rocks are set and 80%+ delivered upon",
    "Submitting monthly reports in on time",
    "Communication policy is followed",
    "Account Queries resolved regularly - Procedures amended to minimise re-occurrence",
    "Operating in a professional manner, including communication and image.",
    "Training received to a high standard whenever required",
    "Creation of Hire Contracts on Protean",
    "Raising and sending Hire Quotes to clients",
    "Following up on quotes sent",
    "Following up on overdue Hire Contracts",
    "Following up on expiring Hire Contracts",
    "Weekly Hire Meetings with Office",
    "Weekly Hire Meetings with Sales",
    "Re-hire of machinery",
    "Checking of machinery pre/post hire",
    "Hire Invoicing",
    "Ensuring hire machines are PDI'd and prepped for hire",
    "Ensuring re-hire machines are maintained appropriately",
    "Solution-focused and able to offer creative options to clients who need more assistance.",
    "Are you proud to work at LVC?",
    "Is there an individual or department that you would like to praise for their work recently?",
    "Do you have any comments or feedback you wish to provide?"
  ]
};

const feedbackQuestions = [
  "Are you proud to work at LVC?",
  "Is there an individual or department that you would like to praise for their work recently?",
  "Do you have any comments or feedback you wish to provide?",
  "Do you have any comments/feedback you wish to make?"
];

function isFeedbackQuestion(text: string): boolean {
  return feedbackQuestions.some(q => text.toLowerCase().includes(q.toLowerCase().substring(0, 30)));
}

function generateTaskId(roleId: string, index: number): string {
  return `${roleId}-task-${index}`;
}

function roleNameToId(roleName: string): string {
  return roleName
    .toLowerCase()
    .replace(/&/g, 'and')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '');
}

export const standardsSurveyData: Record<string, RoleSurvey> = {};

Object.entries(rawSurveyData).forEach(([roleName, tasks]) => {
  const roleId = roleNameToId(roleName);
  standardsSurveyData[roleId] = {
    roleId,
    roleTitle: roleName,
    tasks: tasks.map((text, idx) => ({
      id: generateTaskId(roleId, idx),
      text,
      isFeedback: isFeedbackQuestion(text)
    }))
  };
});

export function getSurveyByRoleId(roleId: string): RoleSurvey | null {
  const normalizedId = roleId.toLowerCase().replace(/[^a-z0-9]+/g, '-');
  
  if (standardsSurveyData[normalizedId]) {
    return standardsSurveyData[normalizedId];
  }
  
  const roleMapping: Record<string, string> = {
    'field-service-engineer': 'field-service-engineer',
    'service-coordinator': 'service-coordinator',
    'service-co-ordinator': 'service-coordinator',
    'workshop-manager': 'workshop-manager',
    'workshop-service-engineer': 'workshop-service-engineer',
    'warehouse-manager': 'warehouse-manager',
    'warehouse-assistant': 'warehouse-assistant',
    'delivery-driver': 'delivery-driver',
    'sales-consultant': 'sales-consultant',
    'hire-controller': 'hire-controller',
    'accounts-administrator': 'accounts-administrator',
    'service-administrator': 'service-administrator',
    'operations-manager': 'operations-manager',
    'hs-quality-coordinator': 'h-and-s-and-quality-coordinator',
    'h-and-s-coordinator': 'h-and-s-and-quality-coordinator',
    'purchase-ledger-administrator': 'purchase-ledger-administrator'
  };
  
  const mappedId = roleMapping[normalizedId];
  if (mappedId && standardsSurveyData[mappedId]) {
    return standardsSurveyData[mappedId];
  }
  
  return null;
}

export function getAllSurveyRoles(): { id: string; title: string }[] {
  return Object.values(standardsSurveyData).map(survey => ({
    id: survey.roleId,
    title: survey.roleTitle
  }));
}
